language: cpp

compiler:
  - gcc
  - clang

os:
  # - linux
  - osx

# command to run tests
before_script:
  - brew update
  - brew unlink boost
  - brew install boost

script: 
  - make
  - make test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)