language: cpp

compiler:
  - gcc
  - clang

os:
  # - linux
  - osx

# command to run tests
before_script:
  - ls /usr/local/Cellar/boost

script: 
  - make
  - make test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)