language: cpp

compiler:
  - gcc
  - clang

os:
  # - linux
  - osx

before_install:
  - brew update
  - brew install boost

# command to run tests
script: 
  - make
  - make test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)