language: cpp

compiler:
  - gcc
  - clang

os:
  # - linux
  - osx

# command to run tests
before_script:
  - brew install boost
#   - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev

script: 
  - make
  - make test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)