language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

# command to run tests
script: 
  - make
  - make test

# env:
#   global:
#     - CODECOV_TOKEN=:uuid-repo-token

after_success:
  - bash <(curl -s https://codecov.io/bash)