sudo: true

language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

# command to run tests
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-test-dev; fi
script: 
  - make
  - make test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)