sudo: true

language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

# command to run tests
install:
  - sudo apt-get install libboost-test-dev
script: 
  - make
  - make test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)